services:
  tor:
    image: "regno/regno-tor:${REGNO_TOR_VERSION}"
    container_name: tor
    build:
      context: ./tor
    restart: always
    command: /tor.sh
    volumes:
      - data-tor:/var/lib/tor
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    networks:
      dmznet:
        ipv4_address: ${NET_DMZ_TOR_IPV4}
      regnonet:
        ipv4_address: ${NET_REGNO_TOR_IPV4}
