version: "3.7"

services:
  monerod:
    image: "regno/monerod:${REGNO_MONEROD_VERSION}"
    build:
      context: ./monerod
      args:
        REGNO_MONEROD_VERSION: ${REGNO_MONEROD_VERSION}
        REGNO_UBUNTU_VERSION: ${REGNO_UBUNTU_VERSION}
    restart: always
    volumes:
      - data-monerod:/home/monero/.bitmonero
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    ports:
      - 18080:18080
      - 18081:18081
    networks:
      regnonet:
        ipv4_address: ${NET_REGNO_MONEROD_IPV4}

  p2pool:
    image: "regno/p2pool:${REGNO_P2POOL_VERSION}"   
    build:
      context: ./p2pool
      args:
        REGNO_P2POOL_VERSION: ${REGNO_P2POOL_VERSION}
        REGNO_UBUNTU_VERSION: ${REGNO_UBUNTU_VERSION}
    networks:
      regnonet:
        ipv4_address: ${NET_REGNO_P2POOL_IPV4}
    ports:
      - ${P2POOL_STRATUM_PORT}:3333/tcp
      - 37888:37888/tcp
      - 37889:37889/tcp
    volumes:
      - p2pool:/home/p2pool/.p2pool:rw
      - /dev/null:/home/p2pool/.p2pool/p2pool.log:rw
      - /dev/hugepages:/dev/hugepages:rw
    depends_on:
      - monerod
    restart: unless-stopped
    command: >-
      --host monerod
      --wallet ${P2POOL_WALLET_ADDRESS}
      --loglevel ${P2POOL_LOGLEVEL}
      {$P2POOL_MINI}

networks:
  regnonet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
  dmznet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/16

volumes:
  data-monerod:
  p2pool: