version: "3.2"

networks:
  regnonet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${REGNONET_SUBNET}
  dmznet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${DMZNET_SUBNET}

volumes:
  data-monerod:
  data-p2pool:
  data-tor:
